import sqlite3 from 'sqlite3';

// GENERATED BY COPILOT (UNREVIEWED)
// Prompt used: "Generate a Project model and a Project service with create, update status, get by team, and delete functions. Use a database."

export interface Project {
  id: string;
  name: string;
  description?: string;
}

const db = new sqlite3.Database(':memory:');

db.serialize(() => {
  db.run('CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, name TEXT, description TEXT)');
});

export const createProject = (p: Project) => new Promise((resolve, reject) => {
  db.run('INSERT INTO projects (id,name,description) VALUES (?,?,?)', [p.id, p.name, p.description], function(err){
    if(err) return reject(err);
    resolve(p);
  });
});

export const updateStatus = (id: string, status: string) => new Promise((resolve,reject)=>{
  // naive: store status in description
  db.run('UPDATE projects SET description = ? WHERE id = ?', [status, id], function(err){
    if(err) return reject(err);
    resolve({id, status});
  });
});

export const getByTeam = (teamId: string) => new Promise((resolve)=>{
  // no team relation; return all
  db.all('SELECT * FROM projects', [], (err, rows)=> resolve(rows));
});

export const deleteProject = (id: string) => new Promise((resolve,reject)=>{
  db.run('DELETE FROM projects WHERE id = ?', [id], function(err){
    if(err) return reject(err);
    resolve();
  });
});
